/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CourseDropping: typeof import('./src/components/student/CourseDropping.vue')['default']
    CourseSchedule: typeof import('./src/components/student/CourseSchedule.vue')['default']
    CourseSelection: typeof import('./src/components/student/CourseSelection.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Error: typeof import('./src/components/Error.vue')['default']
    GradeQuerying: typeof import('./src/components/student/GradeQuerying.vue')['default']
    HeaderUserInfo: typeof import('./src/components/utils/HeaderUserInfo.vue')['default']
    InstructorMain: typeof import('./src/components/instructor/InstructorMain.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    PageHeader: typeof import('./src/components/utils/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudentMain: typeof import('./src/components/student/StudentMain.vue')['default']
    StudentOverall: typeof import('./src/components/student/StudentOverall.vue')['default']
    Teaches: typeof import('./src/components/instructor/Teaches.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
  }
}
